import type { BotHealthItem, Page, TenantItem } from "@/lib/backend-contracts";
import { Pager } from "./pager";

export function BotFleetHealthView({ bots, tenants }: { bots: Page<BotHealthItem>; tenants: TenantItem[] }) {
  const names = new Map(tenants.map((tenant) => [tenant.id, tenant.displayName]));
  return <section className="space-y-6" aria-labelledby="bots-heading"><div className="rounded-xl border border-stone-200 bg-white p-5"><h2 id="bots-heading" className="text-2xl font-bold">Bot fleet health</h2><p className="mt-1 text-sm text-stone-500">Up to 50 bot registrations per page; credentials are never returned.</p></div>
    <div className="overflow-hidden rounded-xl border border-stone-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[60rem] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-4">Bot</th><th className="p-4">Role</th><th className="p-4">Business scope</th><th className="p-4">Shop ID</th><th className="p-4">Registration</th><th className="p-4">Health</th><th className="p-4">Last check</th></tr></thead><tbody className="divide-y divide-stone-200">{bots.items.map((bot) => <tr key={bot.id}><td className="p-4 font-mono font-bold">@{bot.username}</td><td className="p-4 uppercase">{bot.role.replace("_", " ")}</td><td className="p-4">{bot.businessId ? names.get(bot.businessId) ?? bot.businessId : "Global platform"}</td><td className="p-4 font-mono text-xs text-stone-500">{bot.shopId ?? "—"}</td><td className="p-4"><span className="rounded-full border px-3 py-1 text-xs font-bold">{bot.active ? "Active" : "Inactive"}</span></td><td className="p-4"><span className={`rounded-full border px-3 py-1 text-xs font-bold ${bot.healthy ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-red-300 bg-red-50 text-red-700"}`}>{bot.healthy ? "Healthy" : "Needs attention"}</span></td><td className="p-4">{bot.lastHealthAt ? new Date(bot.lastHealthAt).toLocaleString("en-AE", { timeZone: "Asia/Dubai" }) : "No health check"}</td></tr>)}</tbody></table></div>{!bots.items.length && <p className="p-8 text-center text-stone-500">No bot registrations on this page.</p>}<Pager cursorKey="bots_cursor" nextCursor={bots.nextCursor} /></div>
  </section>;
}
