"use client";

import type { ReactNode } from "react";
import { useActionState } from "react";
import { platformAction } from "@/app/actions";
import { INITIAL_ACTION_STATE } from "@/lib/action-state";
import type { TenantItem } from "@/lib/backend-contracts";

function ToolForm({ operation, title, actionNonce, children }: { operation: string; title: string; actionNonce: string; children: ReactNode }) {
  const [state, action, pending] = useActionState(platformAction, INITIAL_ACTION_STATE);
  return <details className="rounded-xl border border-stone-200 bg-white"><summary className="min-h-[52px] cursor-pointer p-4 font-bold">{title}</summary><form action={action} className="space-y-4 border-t border-stone-200 p-5"><input type="hidden" name="operation" value={operation} /><input type="hidden" name="idempotencyKey" value={`ui:${actionNonce}:${operation}`} />{children}{state.status !== "idle" && <p role="status" className={`text-sm ${state.status === "error" ? "text-red-700" : "text-emerald-700"}`}>{state.message}{state.requestId ? ` Request ${state.requestId}.` : ""}</p>}<button disabled={pending} className="min-h-11 rounded bg-stone-900 px-5 font-bold text-yellow-400 disabled:cursor-wait disabled:opacity-60">{pending ? "Saving…" : title}</button></form></details>;
}

const inputClass = "mt-1 min-h-11 w-full rounded border border-stone-300 bg-white px-3";
function Input({ name, label, ...props }: { name: string; label: string; required?: boolean; type?: string; pattern?: string; defaultValue?: string }) { return <label className="block text-sm font-semibold">{label}<input name={name} {...props} className={inputClass} /></label>; }
function Business({ tenants }: { tenants: TenantItem[] }) { return <label className="block text-sm font-semibold">Business<select name="businessId" required className={inputClass}><option value="">Choose business</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.displayName} · {tenant.id}</option>)}</select></label>; }

export function TenantSetupTools({ tenants, actionNonce }: { tenants: TenantItem[]; actionNonce: string }) {
  return <section aria-labelledby="setup-heading"><h3 id="setup-heading" className="mb-3 text-lg font-bold">Shop setup tools</h3><div className="grid gap-4 lg:grid-cols-2">
    <ToolForm operation="create_shop" title="Add shop" actionNonce={actionNonce}><Business tenants={tenants} /><div className="grid gap-3 sm:grid-cols-2"><Input name="shopName" label="Shop name" required /><Input name="internalCode" label="Internal code" required pattern="[A-Za-z0-9_-]+" /><Input name="openTime" label="Opening time" type="time" required defaultValue="09:00" /><Input name="closeTime" label="Closing time" type="time" required defaultValue="22:00" /><Input name="eodTime" label="End-of-day time" type="time" required defaultValue="23:00" /><Input name="defaultServiceMinutes" label="Default service minutes" type="number" required defaultValue="30" /><Input name="paidFrom" label="Coverage from if per-shop" type="date" /><Input name="paidUntil" label="Coverage until if per-shop" type="date" /></div></ToolForm>
    <ToolForm operation="invite_staff" title="Invite staff" actionNonce={actionNonce}><Business tenants={tenants} /><Input name="shopId" label="Shop ID" required /><Input name="email" label="Staff email" type="email" required /><label className="block text-sm font-semibold">Role<select name="role" className={inputClass}><option value="manager">Manager</option><option value="receptionist">Receptionist</option><option value="barber">Barber</option></select></label></ToolForm>
    <ToolForm operation="register_bot" title="Register bot" actionNonce={actionNonce}><Business tenants={tenants} /><Input name="shopId" label="Shop ID" required /><label className="block text-sm font-semibold">Bot role<select name="role" className={inputClass}><option value="customer">Customer</option><option value="receptionist">Reception</option><option value="barber_crew">Barber crew</option><option value="owner">Owner</option></select></label><label className="block text-sm font-semibold">Telegram bot token<input name="botToken" type="password" autoComplete="off" required minLength={20} maxLength={256} className={inputClass} /></label><p className="text-xs text-stone-500">The token is sent only to the backend over the authenticated request and is never displayed again.</p></ToolForm>
    <ToolForm operation="legal_tax" title="Save legal & tax profile" actionNonce={actionNonce}><Business tenants={tenants} /><Input name="shopId" label="Shop ID" required /><Input name="legalName" label="Legal name" required /><Input name="address" label="Address" required /><Input name="tradeLicenseNumber" label="Trade licence number" /><Input name="tradeLicenseExpiry" label="Trade licence expiry" type="date" /><label className="block text-sm font-semibold">VAT registration<select name="vatRegistered" className={inputClass}><option value="false">Not registered</option><option value="true">VAT registered</option></select></label><Input name="trn" label="15-digit TRN if registered" pattern="[0-9]{15}" /><label className="block text-sm font-semibold">Pricing mode<select name="pricingMode" className={inputClass}><option value="vat_inclusive">VAT inclusive</option><option value="vat_exclusive">VAT exclusive</option></select></label></ToolForm>
    <ToolForm operation="change_billing_mode" title="Change billing mode" actionNonce={actionNonce}><Business tenants={tenants} /><label className="block text-sm font-semibold">Target mode<select name="targetMode" className={inputClass}><option value="business">Business-wide</option><option value="per_shop">Per shop</option></select></label><Input name="reason" label="Reason" required /><Input name="confirmScope" label="Type business ID" required /><Input name="confirmConsequence" label="Type CONFIRM" required pattern="CONFIRM" /></ToolForm>
  </div></section>;
}
